version: '3.4'

services:
  caret.legal.microservice:
    image: caret-legal-microservice:dev
    build:
      context: .
      dockerfile: Caret.Legal.Microservice/Dockerfile
  caret.legal.mongo:
    image: mongo:4.4.11
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo 
  caret.legal.redis:
    image: redis:7
    restart: unless-stopped

